disabled_rules: # rule identifiers to exclude from running
  - trailing_comma
  - identifier_name
  - force_try
  - line_length
  - file_length
  - todo
function_body_length:
  - 100
cyclomatic_complexity:
  - 20
type_body_length:
  - 500
excluded:
  - .build
large_tuple:
  - 3