disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_try
  - identifier_name
  - line_length
  - shorthand_operator
  - todo
  - trailing_comma
  - type_body_length
function_body_length:
  - 100
cyclomatic_complexity:
  - 20
type_body_length:
  - 500
excluded:
  - .build
large_tuple:
  - 3