# make sudo to enforce running on a real linux VM and not in a container on a macOS VM.
sudo: required
# do not use swift as language, since otherwise the build always runs on a macOS VM.
language: generic

compiler:
  - clang

jobs:
  include:
    - os: osx
      osx_image: xcode12.5
      env: SWIFT_VERSION=5.0
    - os: osx
      osx_image: xcode12.5
      env: SWIFT_VERSION=5.1
    - os: osx
      osx_image: xcode12.5
      env: SWIFT_VERSION=5.2
    - os: osx
      osx_image: xcode12.5
      env: SWIFT_VERSION=5.3
    - os: osx
      osx_image: xcode12.5
      env: SWIFT_VERSION=5.4

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swift --version

script:
  - swift build
  - swift test
  - |
    # lint on osx only (no need to do this on every platform)
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swiftlint --strict
    fi
