name: ci
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.2.1
  test:
    strategy:
      matrix:
        swift-version:
          - "5.5"
          - "5.4"
          - "5.3"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - run: swift test
